title: Meghana Appidi
logo: "/Meghana.png"
description: >
  <br>
  R&D Engineer | User researcher
  <br>
  <a href="https://www.linkedin.com/in/meghana-appidi-111a41187/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:ma8261@nyu.edu">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
